FROM python:3.11-slim

# Instalar herramientas necesarias
RUN apt-get update && apt-get install -y git netcat-openbsd && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app/backend

COPY requirements.txt /app/requirements.txt
COPY backend /app/backend

RUN pip install --no-cache-dir -r /app/requirements.txt

EXPOSE 8000

CMD ["sh", "-c", "uvicorn main:app --host 0.0.0.0 --port 8000"]
